channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.5.1
  - samtools=1.1
  - biopython=1.68
  - snakemake=3.8.2
  - pyyaml=3.11
  - bedtools=2.17.0
  - ucsc-bedgraphtobigwig=332 
  - bowtie2=2.3.0
  - pandas=0.19.2
<<<<<<< HEAD
  #- shortstack=3.6
=======
>>>>>>> f9c8a531907ee118fe06e22f682c1b788c5cec98

