#!/usr/bin/env Rscript
##############################################################################
### Makes one coverage plot per gene from coverage data and a bed file

# Coverage file format (coverage at the base level)
#chr   pos depth
#SL3.0ch01 46063     2
#SL3.0ch01 46064     2
#SL3.0ch01 46065     2
#SL3.0ch01 46066     2
#SL3.0ch01 46067     2
#SL3.0ch01 46068     2

# bed file format are six fields (chr/start/end/gene/score/strand)

#Usage
# Rscript --vanilla create_target_plots.R --coverage [coverage file] --bedfile [bedfile]--outdir [outdir]
# Arguments: 
#     coverage: a coverage file generated by samtools depth 
#     bedfile:  a bedfile for the regions of interest (e.g. genes)
#     outdir:   the directory where results should be stored 
#####################################################################

#######################################
# Libraries and command-line arguments
######################################
# load libraries 
library(optparse)
library(dplyr,quietly = TRUE,warn.conflicts = F,verbose = F)
library(svglite,verbose = F)
library(ggplot2,verbose = F)

# parse command line arguments
option_list = list(
  make_option(c("-i", "--coverage"), type="character", default=NULL,help="input file of coverage data", metavar="character"),
  make_option(c("-b", "--bedfile"), type="character",default="NA",help="bed file of interesting regions"),
  make_option(c("-o", "--outdir"), type="character",default="NA",help="output directory for plots")
) 
opt_parser = OptionParser(option_list=option_list);
args = parse_args(opt_parser)

#args$coverage = "~/SURFdrive/trichome_team/11.analysis/sRNA/degradome/20170828_degradome/C32.cov"
#args$bedfile = "~/SURFdrive/trichome_team/11.analysis/sRNA/degradome/20170828_degradome/parsed.bed"
#args$outdir = "~/SURFdrive/trichome_team/11.analysis/sRNA/degradome/20170828_degradome/plots/"

# removes old plot directory (with same name)
# creates directory if it does not exist
unlink("plots/",force = T,recursive = T)
dir.create(args$outdir,recursive = T,showWarnings = F)


##################
# Read input files
##################
cov = read.delim(args$coverage,header = F,stringsAsFactors = F,col.names = c("chr","pos","depth"))
bed = read.delim(args$bedfile,header = F,stringsAsFactors = F,col.names = c("chr","start","end","gene","score","strand"))

# non-redundant list of genes for which a coverage plot should be made
genes = unique(bed$gene)  

#################
# Coverage plots
################
# make coverage plots (one per gene)
for (i in seq_along(genes)){
  # Creates a BED file for the gene of interest
  selected_gene = genes[i]
  mini_bed = dplyr::filter(bed,gene == selected_gene)
  start = as.integer(mini_bed$start)
  end = as.integer(mini_bed$end)
  
  # Filter the coverage file using the extracted coordinates
  mini_cov = cov %>%
    filter(pos >= start & pos <= end)
  
  ########## make and save plot #########
  # get the maximum value for this particular gene
  maximum = max(mini_cov$depth)
  text2add = filter(mini_cov,depth >= maximum)$pos # to retrieve the max position
  text2add = paste(text2add,collapse=" ") # if multiple positions have the same maximum
  
  plot.title = paste(selected_gene,"\n","positions: ",text2add,sep = "")
  g <- ggplot(mini_cov) + 
    geom_point(aes(pos,depth,colour=depth>=maximum)) +
    scale_colour_manual(
      name="Maximum PARE counts",
      values=setNames(c("red","black"),c(TRUE,FALSE))) +
    labs(x=paste("Position on",mini_bed$chr,sep=" "),y="Read counts") +
    ggtitle(plot.title) +
    # removes legend
    theme(legend.position="none") +
    theme(plot.title = element_text(size=10))

    
  # save plot (png and pdf)
  ggsave(file.path(args$outdir,paste(selected_gene,".png")),plot=g,width=9,height=8,units = "cm")
  ggsave(file.path(args$outdir,paste(selected_gene,".pdf")),plot=g,width=9,height=8)
  
}


